=== Balirina/Heaven-Hotel/Schema/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="heavenHotel">
	<xs:complexType>
			<xs:sequence>
				<xs:element name="VAT" type="xs:string"/>	
				<xs:element name="roomRent" type="Renttype"/>
				<xs:element name="restaurant" type="restauranttype"/>
				<xs:element name="spaCare" type="spaCaretype"/>
			</xs:sequence>
	</xs:complexType>
</xs:element>
	
	<xs:complexType name="Renttype">
		<xs:sequence>
				<xs:element name="rooms" type="habitactype" minOccurs="1" maxOccurs="unbounded"/>				
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="habitactype">
		<xs:sequence>
			<xs:element name="room" type="roomtype" minOccurs="1" maxOccurs="unbounded"/>	
		</xs:sequence>
			<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="roomtype">
		<xs:sequence>
			<xs:element name="bedroom" type="xs:string"/>	
			<xs:element name="kitchen">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="All inclusive"/>
						<xs:enumeration value="Breakfast and lunch included"/>
						<xs:enumeration value="Breakfast included"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="airConditioning" type="airCondtype"/>	
			<xs:element name="roomsService" type="xs:string"/>	
			<xs:element name="price" type="pricetype"/>	
			<xs:element name="discount">	
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="0.0"/>
						<xs:maxInclusive value="0.3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="imagen" type="imagentype"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="airCondtype">
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="imagentype">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="pagina" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="pricetype">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="currency" type="xs:string" fixed="euro"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="restauranttype">
		<xs:sequence>
			<xs:element name="ChickenMenu" type="ChickenMenutype"/>
			<xs:element name="VeganMenu" type="VeganMenutype"/>
			<xs:element name="Salads" type="Saladstype"/>
			<xs:element name="Desserts" type="Dessertstype"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ChickenMenutype">
		<xs:sequence>
			<xs:element name="dish" type="dishtype"  minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="dishtype">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="category" type="xs:string"/>
			<xs:element name="calories">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="preparingTime" type="xs:string"/>
			<xs:element name="ingredients" type="xs:string"/>
			<xs:element name="price" type="pricetype"/>
			<xs:element name="imagen" type="imagentype"/>
		</xs:sequence>
		<xs:attribute name="cod" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="VeganMenutype">
		<xs:sequence>
			<xs:element name="dish" type="dishtype"  minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Saladstype">
		<xs:sequence>
			<xs:element name="dish" type="dishtype"  minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="Dessertstype">
		<xs:sequence>
			<xs:element name="dish" type="dishtype"  minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="spaCaretype">
		<xs:sequence>
			<xs:element name="service" type="servicetype" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType> 
	
	<xs:complexType name="servicetype">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="duration" type="durationtype"/>
			<xs:element name="price" type="pricetype"/>
			<xs:element name="discount" type="xs:decimal"/>
			<xs:element name="imagen" type="imagentype"/>
		</xs:sequence>
		<xs:attribute name="codigo" type="xs:string" use="required"/>
	</xs:complexType>
	

	<xs:complexType name="durationtype">
		<xs:simpleContent>
			<xs:extension base="xs:decimal">
				<xs:attribute name="measure" type="xs:string" fixed="hours"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
</xs:schema>

=== Balirina/Heaven-Hotel/xml/index_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE heavenHotel[
<!ELEMENT heavenHotel (VAT, roomRent, restaurant, spaCare)>
	<!ELEMENT VAT (#PCDATA)>
	<!--RoomRent Service-->
	<!ELEMENT roomRent (rooms+)>
	<!ELEMENT cityTax (#PCDATA)>
	<!ELEMENT rooms (room+)>
	<!ATTLIST rooms  type (luxury | standard | economy) #REQUIRED >
	<!ELEMENT room (bedroom, kitchen, airConditioning, roomsService, price, discount?,imagen)>
	<!ATTLIST room  id (president | king | business | single | double |triple) #REQUIRED >
	<!ELEMENT bedroom (#PCDATA)>
	<!ELEMENT kitchen (#PCDATA)>
	<!ELEMENT airConditioning EMPTY>
	<!ATTLIST airConditioning  id (Yes| No) #REQUIRED >
	<!ELEMENT roomsService (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT discount (#PCDATA)>
	<!ELEMENT imagen (#PCDATA)>
	<!--restaurant products-->
	<!ELEMENT restaurant (ChickenMenu, VeganMenu, Salads, Desserts)>
	<!--ChickenMenu-->
	<!ELEMENT ChickenMenu (dish+)>
	<!ELEMENT dish (name, description, category, calories, preparingTime, ingredients, price, imagen)>
	<!ATTLIST dish  cod (CM1 | CM2 | CM3 | CM4 | CM5 | CM6 | CM7 | CM8 |VG1 | VG2 | VG3 | VG4 |SLD1 | SLD2 | SLD3 | SLD4 | DST1 | DST2 | DST3 | DST4) #REQUIRED >
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT category (#PCDATA)>
	<!ELEMENT calories (#PCDATA)>
	<!ELEMENT preparingTime (#PCDATA)>
	<!ELEMENT ingredients (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT imagen (#PCDATA)>
	<!--VeganMenu-->
	<!ELEMENT VeganMenu (dish+)>
	<!ELEMENT dish (name, description, category, calories, preparingTime, ingredients, price, imagen)>
	<!ATTLIST dish  cod (VG1 | VG2 | VG3 | VG4) #REQUIRED >
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT category (#PCDATA)>
	<!ELEMENT calories (#PCDATA)>
	<!ELEMENT preparingTime (#PCDATA)>
	<!ELEMENT ingredients (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT imagen (#PCDATA)>
	<!--Salads-->
	<!ELEMENT Salads (dish+)>
	<!ELEMENT dish (name, description, category, calories, preparingTime, ingredients, price,imagen)>
	<!ATTLIST dish  cod (SLD1 | SLD2 | SLD3 | SLD4) #REQUIRED >
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT category (#PCDATA)>
	<!ELEMENT calories (#PCDATA)>
	<!ELEMENT preparingTime (#PCDATA)>
	<!ELEMENT ingredients (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT imagen (#PCDATA)>
	<!--Desserts--> 
	<!ELEMENT Desserts (dish+)>
	<!ELEMENT dish (name, description, category, calories, preparingTime, ingredients, price, imagen)>
	<!ATTLIST dish  cod (DST1 | DST2 | DST3 | DST4) #REQUIRED >
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT category (#PCDATA)>
	<!ELEMENT calories (#PCDATA)>
	<!ELEMENT preparingTime (#PCDATA)>
	<!ELEMENT ingredients (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT imagen (#PCDATA)>
	<!--Spa and care services-->
	<!ELEMENT spaCare (service+)>
	<!ELEMENT service (name, description, duration, price, discount?,imagen)>
	<!ATTLIST service  codigo (Spa1 | Spa2 | Spa3) #REQUIRED >
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT duration (#PCDATA)>
	<!ATTLIST duration measure (hours) #REQUIRED >
	<!ELEMENT price (#PCDATA)>
	<!ATTLIST price currency (euro) #REQUIRED >
	<!ELEMENT discount (#PCDATA)>
	<!ELEMENT imagen (#PCDATA)>
	]>
<heavenHotel><!-- xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"  xs:noNamespaceSchemaLocation="../Schema/index.xsd"-->
	<VAT>1.2</VAT>
	<roomRent>
		<!--The rooms of type luxury-->
		<rooms type="luxury">
			<room id="president">
				<bedroom>1 president size bed</bedroom>
				<kitchen>All inclusive</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">359</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room10.jpg</imagen> 
			</room>
			<room id="president">
				<bedroom>1 president size bed</bedroom>
				<kitchen>All inclusive</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">359</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room8.jpg</imagen> 
			</room>
			<room id="king">
				<bedroom>1 king size bed</bedroom>
				<kitchen>All inclusive</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">296</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room11.jpg</imagen> 
			</room>
			<room id="king">
				<bedroom>1 king size bed</bedroom>
				<kitchen>All inclusive</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">289</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room6.jpg</imagen> 
			</room>
			<room id="business">
				<bedroom>1 large size bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">254</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room4.jpg</imagen> 
			</room>
			<room id="business">
				<bedroom>1 large size bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">253</price>
				<discount>0.1</discount>
				<imagen pagina="www.nh-hoteles.es">room12.jpg</imagen> 
			</room>
		</rooms>
		<!--The rooms of type standard-->
		<rooms type="standard">
			<room id="single">
				<bedroom>1 large bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">159</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room14.jpg</imagen> 
			</room>
			<room id="single">
				<bedroom>1 large double bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning  id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">148</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room2.jpg</imagen> 
			</room>
			<room id="double">
				<bedroom>1 large double bed, 1 single bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">189</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room5.jpg</imagen> 
			</room>
			<room id="double">
				<bedroom>1 large double bed, 1 single bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">169</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room13.jpg</imagen> 
			</room>
			<room id="triple">
				<bedroom>1 large double bed, 1 single bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">219</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room3.jpg</imagen> 
			</room>
			<room id="triple">
				<bedroom>1 large double bed, 1 single bed</bedroom>
				<kitchen>Breakfast and lunch included</kitchen>
				<airConditioning id="Yes"></airConditioning>
				<roomsService>From 06:00 till 22:00</roomsService>
				<price currency="euro">199</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room15.jpg</imagen> 
			</room>
		</rooms>
		<!--The rooms of type economy-->
		<rooms type="economy">
			<room id="single">
				<bedroom>1 large single bed</bedroom>
				<kitchen>Breakfast included</kitchen>
				<airConditioning id="No"></airConditioning>
				<roomsService>Not included</roomsService>
				<price currency="euro">89</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room9.jpg</imagen> 
			</room>
			<room id="single">
				<bedroom>1 large single bed</bedroom>
				<kitchen>Breakfast included</kitchen>
				<airConditioning id="No"></airConditioning>
				<roomsService>Not included</roomsService>
				<price currency="euro">93</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room7.jpg</imagen> 
			</room>
			<room id="double">
				<bedroom>1 large double bed</bedroom>
				<kitchen>Breakfast included</kitchen>
				<airConditioning id="No"></airConditioning>
				<roomsService>Not included</roomsService>
				<price currency="euro">113</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room16.jpg</imagen> 
			</room>
			<room id="double">
				<bedroom>1 large double bed</bedroom>
				<kitchen>Breakfast included</kitchen>
				<airConditioning id="No"></airConditioning>
				<roomsService>Not included</roomsService>
				<price currency="euro">127</price>
				<discount>0.15</discount>
				<imagen pagina="www.nh-hoteles.es">room1.jpg</imagen> 
			</room>
			<room id="triple">
				<bedroom>1 large double bed, 1 single bed</bedroom>
				<kitchen>Breakfast included</kitchen>
				<airConditioning id="No"></airConditioning>
				<roomsService>Not included</roomsService>
